# chips_imagens.py
# Dicionário que mapeia o nome dos chips (em minúsculas) para suas URLs de imagem.

chips_imagens = {
    "airhockey": "https://media.discordapp.net/attachments/1141184113668268064/1397067300431204495/BN4Chip063_1.png?ex=68805fd0&is=687f0e50&hm=456ca0fc7e5705dca8d9421a6b782a0db1b7d2ede5486cc5d8dc316004107ee0&=&width=624&height=534",
    "airraid": "https://example.com/airraid.png",
    "airraid 2": "https://example.com/airraid2.png",
    "airraid 3": "https://example.com/airraid3.png",
    "airshot": "https://example.com/airshot.png",
    "airspin": "https://example.com/airspin.png",
    "airspin 2": "https://example.com/airspin2.png",
    "airspin 3": "https://example.com/airspin3.png",
    "antisword": "https://example.com/antisword.png",
    "anubis": "https://example.com/anubis.png",
    "aquadragon": "https://example.com/aquadragon.png",
    "aquaneedle": "https://example.com/aquaneedle.png",
    "aquaneedle 2": "https://example.com/aquaneedle2.png",
    "aquaneedle 3": "https://example.com/aquaneedle3.png",
    "aquasword": "https://example.com/aquasword.png",
    "areagrab": "https://example.com/areagrab.png",
    "assassinsword": "https://example.com/assassinsword.png",
    "aurahead": "https://example.com/aurahead.png",
    "aurahead 2": "https://example.com/aurahead2.png",
    "aurahead 3": "https://example.com/aurahead3.png",
    "autumnal": "https://example.com/autumnal.png",
    "bamboosword": "https://example.com/bamboosword.png",
    "barrier": "https://example.com/barrier.png",
    "barrier 10": "https://example.com/barrier10.png",
    "barrier 5": "https://example.com/barrier5.png",
    "bazooka": "https://example.com/bazooka.png",
    "bazooka!": "https://example.com/bazooka_exclamation.png",
    "bigbomb": "https://example.com/bigbomb.png",
    "blackbomb": "https://example.com/blackbomb.png",
    "blizzardball": "https://example.com/blizzardball.png",
    "boomer": "https://example.com/boomer.png",
    "bubbler": "https://example.com/bubbler.png",
    "bubblestar": "https://example.com/bubblestar.png",
    "bubblestar 2": "https://example.com/bubblestar2.png",
    "bubblestar 3": "https://example.com/bubblestar3.png",
    "bubblewrap": "https://example.com/bubblewrap.png",
    "bugfix": "https://example.com/bugfix.png",
    "burnsquare": "https://example.com/burnsquare.png",
    "burnsquare 2": "https://example.com/burnsquare2.png",
    "burnsquare 3": "https://example.com/burnsquare3.png",
    "candle": "https://example.com/candle.png",
    "cannon": None,
    "charge": "https://example.com/charge.png",
    "circulargun": "https://example.com/circulargun.png",
    "copydamage": "https://example.com/copydamage.png",
    "cornshot": "https://example.com/cornshot.png",
    "cornshot 2": "https://example.com/cornshot2.png",
    "cornshot 3": "https://example.com/cornshot3.png",
    "crakshot": "https://example.com/crakshot.png",
    "crossgun": "https://example.com/crossgun.png",
    "customsword": "https://example.com/customsword.png",
    "damagepass": "https://example.com/damagepass.png",
    "discharge": "https://example.com/discharge.png",
    "discord": "https://example.com/discord.png",
    "dollthunder": "https://example.com/dollthunder.png",
    "dollthunder 2": "https://example.com/dollthunder2.png",
    "dollthunder 3": "https://example.com/dollthunder3.png",
    "doubleshot": "https://example.com/doubleshot.png",
    "drillarm": "https://example.com/drillarm.png",
    "duel": "https://example.com/duel.png",
    "elecdragon": "https://example.com/elecdragon.png",
    "elecpulse": "https://example.com/elecpulse.png",
    "elecpulse 2": "https://example.com/elecpulse2.png",
    "elecpulse 3": "https://example.com/elecpulse3.png",
    "elecsword": "https://example.com/elecsword.png",
    "elementalsword": "https://example.com/elementalsword.png",
    "energybomb": "https://example.com/energybomb.png",
    "fanfare": "https://example.com/fanfare.png",
    "fastgauge": "https://example.com/fastgauge.png",
    "fireburner": "https://example.com/fireburner.png",
    "fireburner 2": "https://example.com/fireburner2.png",
    "fireburner 3": "https://example.com/fireburner3.png",
    "firehit": "https://example.com/firehit.png",
    "firehit 2": "https://example.com/firehit2.png",
    "firehit 3": "https://example.com/firehit3.png",
    "firesword": "https://example.com/firesword.png",
    "fist": "https://example.com/fist.png",
    "flaregun": "https://example.com/flaregun.png",
    "flashbomb": "https://example.com/flashbomb.png",
    "flashbomb 2": "https://example.com/flashbomb2.png",
    "flashbomb 3": "https://example.com/flashbomb3.png",
    "folderback": "https://example.com/folderback.png",
    "fullcustom": "https://example.com/fullcustom.png",
    "grabbanish": "https://example.com/grabbanish.png",
    "grabrevanche": "https://example.com/grabrevanche.png",
    "grassseed": "https://example.com/grassseed.png",
    "grassstage": "https://example.com/grassstage.png",
    "guardian": "https://example.com/guardian.png",
    "gundelsol": "https://example.com/gundelsol.png",
    "gundelsol 2": "https://example.com/gundelsol2.png",
    "gundelsol 3": "https://example.com/gundelsol3.png",
    "heatdragon": "https://example.com/heatdragon.png",
    "heatincrease": "https://example.com/heatincrease.png",
    "heatshot": "https://example.com/heatshot.png",
    "highboomer": "https://example.com/highboomer.png",
    "highcannon": "https://example.com/highcannon.png",
    "iceseed": "https://example.com/iceseed.png",
    "icestage": "https://example.com/icestage.png",
    "interrupt": "https://example.com/interrupt.png",
    "invisible": "https://example.com/invisible.png",
    "ironshield": "https://example.com/ironshield.png",
    "ironshield 2": "https://example.com/ironshield2.png",
    "ironshield 3": "https://example.com/ironshield3.png",
    "jealousy": "https://example.com/jealousy.png",
    "katana": "https://example.com/katana.png",
    "kunai": "https://example.com/kunai.png",
    "lance": "https://example.com/lance.png",
    "lavastage": "https://example.com/lavastage.png",
    "littleboiler": "https://example.com/littleboiler.png",
    "littleboiler 2": "https://example.com/littleboiler2.png",
    "littleboiler 3": "https://example.com/littleboiler3.png",
    "longblade": "https://example.com/longblade.png",
    "longsword": "https://example.com/longsword.png",
    "machinegun": "https://example.com/machinegun.png",
    "machinegun 2": "https://example.com/machinegun2.png",
    "machinegun 3": "https://example.com/machinegun3.png",
    "machinesword": "https://example.com/machinesword.png",
    "magneticcoil": "https://example.com/magneticcoil.png",
    "magnum": "https://example.com/magnum.png",
    "manequino": "https://example.com/manequino.png",
    "megaboomer": "https://example.com/megaboomer.png",
    "megacannon": "https://example.com/megacannon.png",
    "megaenergybomb": "https://example.com/megaenergybomb.png",
    "metalstage": "https://example.com/metalstage.png",
    "meteors": "https://example.com/meteors.png",
    "mine": "https://example.com/mine.png",
    "minibomb": "https://example.com/minibomb.png",
    "molokorush": "https://example.com/molokorush.png",
    "molokorush 2": "https://example.com/molokorush2.png",
    "molokorush 3": "https://example.com/molokorush3.png",
    "moonblade": "https://example.com/moonblade.png",
    "moonlight": "https://example.com/moonlight.png",
    "muramasa": "https://example.com/muramasa.png",
    "needlesword": "https://example.com/needlesword.png",
    "needlesword 2": "https://example.com/needlesword2.png",
    "neovariable": "https://example.com/neovariable.png",
    "northwind": "https://example.com/northwind.png",
    "numberball": "https://example.com/numberball.png",
    "panelgrab": "https://example.com/panelgrab.png",
    "poisonstage": "https://example.com/poisonstage.png",
    "puddle": "https://example.com/puddle.png",
    "rainstorm": "https://example.com/rainstorm.png",
    "recovery 10": "https://example.com/recovery10.png",
    "recovery 15": "https://example.com/recovery15.png",
    "recovery 25": "https://example.com/recovery25.png",
    "recovery 30": "https://example.com/recovery30.png",
    "recovery 5": "https://example.com/recovery5.png",
    "reflector 1": "https://example.com/reflector1.png",
    "reflector 2": "https://example.com/reflector2.png",
    "reflector 3": "https://example.com/reflector3.png",
    "repair": "https://example.com/repair.png",
    "riskyhoney": "https://example.com/riskyhoney.png",
    "riskyhoney 2": "https://example.com/riskyhoney2.png",
    "riskyhoney 3": "https://example.com/riskyhoney3.png",
    "rockcube": "https://example.com/rockcube.png",
    "rollinglog": "https://example.com/rollinglog.png",
    "rollinglog 2": "https://example.com/rollinglog2.png",
    "rollinglog 3": "https://example.com/rollinglog3.png",
    "rope": "https://example.com/rope.png",
    "sandstage": "https://example.com/sandstage.png",
    "sandworm": "https://example.com/sandworm.png",
    "sandworm 2": "https://example.com/sandworm2.png",
    "sandworm 3": "https://example.com/sandworm3.png",
    "sensor": "https://example.com/sensor.png",
    "sensor 2": "https://example.com/sensor2.png",
    "sensor 3": "https://example.com/sensor3.png",
    "shockwave": "https://example.com/shockwave.png",
    "shotgun": "https://example.com/shotgun.png",
    "silence": "https://example.com/silence.png",
    "slowgauge": "https://example.com/slowgauge.png",
    "snake": "https://example.com/snake.png",
    "snowystep": "https://example.com/snowystep.png",
    "spreader": "https://example.com/spreader.png",
    "spreader 2": "https://example.com/spreader2.png",
    "spreader 3": "https://example.com/spreader3.png",
    "static": "https://example.com/static.png",
    "stepsword": "https://example.com/stepsword.png",
    "stonebody": "https://example.com/stonebody.png",
    "strongfist": "https://example.com/strongfist.png",
    "summonblack": "https://example.com/summonblack.png",
    "summonblack 2": "https://example.com/summonblack2.png",
    "summonblack 3": "https://example.com/summonblack3.png",
    "sunburst": "https://example.com/sunburst.png",
    "sunburst!": "https://example.com/sunburst_exclamation.png",
    "super vulcan": "https://example.com/supervulcan.png",
    "sword": "https://example.com/sword.png",
    "tankcannon": "https://example.com/tankcannon.png",
    "tankcannon 2": "https://example.com/tankcannon2.png",
    "tankcannon 3": "https://example.com/tankcannon3.png",
    "thunder": "https://example.com/thunder.png",
    "timebomb": "https://example.com/timebomb.png",
    "timebomb 2": "https://example.com/timebomb2.png",
    "timebomb 3": "https://example.com/timebomb3.png",
    "tornado": "https://example.com/tornado.png",
    "trainarrow": "https://example.com/trainarrow.png",
    "trainarrow 2": "https://example.com/trainarrow2.png",
    "trainarrow 3": "https://example.com/trainarrow3.png",
    "treevie": "https://example.com/treevie.png",
    "trickrtret": "https://example.com/trickrtret.png",
    "tripleshot": "https://example.com/tripleshot.png",
    "v-gun": "https://example.com/v-gun.png",
    "variablesword": "https://example.com/variablesword.png",
    "vulcan": "https://example.com/vulcan.png",
    "vulcan 2": "https://example.com/vulcan2.png",
    "vulcan 3": "https://example.com/vulcan3.png",
    "wavearm": "https://example.com/wavearm.png",
    "wavearm 2": "https://example.com/wavearm2.png",
    "wavearm 3": "https://example.com/wavearm3.png",
    "wideblade": "https://example.com/wideblade.png",
    "wideshot": "https://example.com/wideshot.png",
    "widesword": "https://example.com/widesword.png",
    "windlock": "https://example.com/windlock.png",
    "windrack": "https://example.com/windrack.png",
    "windstage": "https://example.com/windstage.png",
    "wooddragon": "https://example.com/wooddragon.png",
    "wrap": "https://example.com/wrap.png",
    "yoyo": "https://example.com/yoyo.png",
    "z-saber": "https://example.com/z-saber.png",
    "zapring": "https://example.com/zapring.png"
}
