# chips_imagens.py
# Dicionário que mapeia o nome dos chips (em minúsculas) para suas URLs de imagem.

chips_imagens = {
    "airhockey": "https://media.discordapp.net/attachments/1141184113668268064/1397067300431204495/BN4Chip063_1.png?ex=68805fd0&is=687f0e50&hm=456ca0fc7e5705dca8d9421a6b782a0db1b7d2ede5486cc5d8dc316004107ee0&=&width=624&height=534",
    "airraid": None,
    "airraid 2": None,
    "airraid 3": None,
    "airshot": None,
    "airspin": None,
    "airspin 2": None,
    "airspin 3": None,
    "antisword": None,
    "anubis": None,
    "aquadragon": None,
    "aquaneedle": None,
    "aquaneedle 2": None,
    "aquaneedle 3": None,
    "aquasword": None,
    "areagrab": None,
    "assassinsword": None,
    "aurahead": None,
    "aurahead 2": None,
    "aurahead 3": None,
    "autumnal": None,
    "bamboosword": None,
    "barrier": None,
    "barrier 10": None,
    "barrier 5": None,
    "bazooka": None,
    "bazooka!": None,
    "bigbomb": None,
    "blackbomb": None,
    "blizzardball": None,
    "boomer": None,
    "bubbler": None,
    "bubblestar": None,
    "bubblestar 2": None,
    "bubblestar 3": None,
    "bubblewrap": None,
    "bugfix": None,
    "burnsquare": None,
    "burnsquare 2": None,
    "burnsquare 3": None,
    "candle": None,
    "cannon": None,
    "charge": None,
    "circulargun": None,
    "copydamage": None,
    "cornshot": None,
    "cornshot 2": None,
    "cornshot 3": None,
    "crakshot": None,
    "crossgun": None,
    "customsword": None,
    "damagepass": None,
    "discharge": None,
    "discord": None,
    "dollthunder": None,
    "dollthunder 2": None,
    "dollthunder 3": None,
    "doubleshot": None,
    "drillarm": None,
    "duel": None,
    "elecdragon": None,
    "elecpulse": None,
    "elecpulse 2": None,
    "elecpulse 3": None,
    "elecsword": None,
    "elementalsword": None,
    "energybomb": None,
    "fanfare": None,
    "fastgauge": None,
    "fireburner": None,
    "fireburner 2": None,
    "fireburner 3": None,
    "firehit": None,
    "firehit 2": None,
    "firehit 3": None,
    "firesword": None,
    "fist": None,
    "flaregun": None,
    "flashbomb": None,
    "flashbomb 2": None,
    "flashbomb 3": None,
    "folderback": None,
    "fullcustom": None,
    "grabbanish": None,
    "grabrevanche": None,
    "grassseed": None,
    "grassstage": None,
    "guardian": None,
    "gundelsol": None,
    "gundelsol 2": None,
    "gundelsol 3": None,
    "heatdragon": None,
    "heatincrease": None,
    "heatshot": None,
    "highboomer": None,
    "highcannon": None,
    "iceseed": None,
    "icestage": None,
    "interrupt": None,
    "invisible": None,
    "ironshield": None,
    "ironshield 2": None,
    "ironshield 3": None,
    "jealousy": None,
    "katana": None,
    "kunai": None,
    "lance": None,
    "lavastage": None,
    "littleboiler": None,
    "littleboiler 2": None,
    "littleboiler 3": None,
    "longblade": None,
    "longsword": None,
    "machinegun": None,
    "machinegun 2": None,
    "machinegun 3": None,
    "machinesword": None,
    "magneticcoil": None,
    "magnum": None,
    "manequino": None,
    "megaboomer": None,
    "megacannon": None,
    "megaenergybomb": None,
    "metalstage": None,
    "meteors": None,
    "mine": None,
    "minibomb": None,
    "molokorush": None,
    "molokorush 2": None,
    "molokorush 3": None,
    "moonblade": None,
    "moonlight": None,
    "muramasa": None,
    "needlesword": None,
    "needlesword 2": None,
    "neovariable": None,
    "northwind": None,
    "numberball": None,
    "panelgrab": None,
    "poisonstage": None,
    "puddle": None,
    "rainstorm": None,
    "recovery 10": None,
    "recovery 15": None,
    "recovery 25": None,
    "recovery 30": None,
    "recovery 5": None,
    "reflector 1": None,
    "reflector 2": None,
    "reflector 3": None,
    "repair": None,
    "riskyhoney": None,
    "riskyhoney 2": None,
    "riskyhoney 3": None,
    "rockcube": None,
    "rollinglog": None,
    "rollinglog 2": None,
    "rollinglog 3": None,
    "rope": None,
    "sandstage": None,
    "sandworm": None,
    "sandworm 2": None,
    "sandworm 3": None,
    "sensor": None,
    "sensor 2": None,
    "sensor 3": None,
    "shockwave": None,
    "shotgun": None,
    "silence": None,
    "slowgauge": None,
    "snake": None,
    "snowystep": None,
    "spreader": None,
    "spreader 2": None,
    "spreader 3": None,
    "static": None,
    "stepsword": None,
    "stonebody": None,
    "strongfist": None,
    "summonblack": None,
    "summonblack 2": None,
    "summonblack 3": None,
    "sunburst": None,
    "sunburst!": None,
    "super vulcan": None,
    "sword": None,
    "tankcannon": None,
    "tankcannon 2": None,
    "tankcannon 3": None,
    "thunder": None,
    "timebomb": None,
    "timebomb 2": None,
    "timebomb 3": None,
    "tornado": None,
    "trainarrow": None,
    "trainarrow 2": None,
    "trainarrow 3": None,
    "treevie": None,
    "trickrtret": None,
    "tripleshot": None,
    "v-gun": None,
    "variablesword": None,
    "vulcan": None,
    "vulcan 2": None,
    "vulcan 3": None,
    "wavearm": None,
    "wavearm 2": None,
    "wavearm 3": None,
    "wideblade": None,
    "wideshot": None,
    "widesword": None,
    "windlock": None,
    "windrack": None,
    "windstage": None,
    "wooddragon": None,
    "wrap": None,
    "yoyo": None,
    "z-saber": None,
    "zapring": None
}
